# Generated by Django 2.2.16 on 2022-04-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220420_1301'),
        ('reviews', '0002_auto_20220420_1110'),
    ]

    operations = [
    ]
